import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-international-phone/style.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import { CustomThemeProvider } from "@/shared/ui/custom-theme-provider";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable}  antialiased  m-[0px] h-[100vh] `}
      >
        <Script
          src="https://22901a9fe14d.us-east-1.captcha-sdk.awswaf.com/22901a9fe14d/jsapi.js"
          strategy="afterInteractive"
        />
        <CustomThemeProvider>{children}</CustomThemeProvider>
      </body>
    </html>
  );
}
